name: lionel3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - pip
  - ipykernel
  - pymc>=5
  - pymc-marketing>=0.9.0
  - arviz=0.19.0
  - seaborn
  - pip:
    - pulp
