name: lionel-forecasting
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - plotly
  - ipykernel
  - pytest
  - pytorch
  - neuralforecast
  - statsforecast
  - matplotlib
  - mlforecast
  - lightgbm
  - pymc3
  - arviz
  - bambi
  - seaborn
  - numba
  - aesara
  - pip:
    - pulp
    - python-dotenv
    - pandas
    - numpy
    - requests
